In [1]:
#===============================
# Translation from pure python to notebook for easier read!
#===============================
import numpy as np

In [2]:
# Method to calculate Min-edit-distance
def mineditdistance(source_word, target_word, show_grid = False):
    n = len(source_word) + 1
    m = len(target_word) + 1
    D = np.zeros((n, m))
    
    # Initialize column 0
    for i in range(1, n):
        D[i,0] = D[i - 1, 0] + 1
    # Initialize row 0
    for j in range(1, m):
        D[0,j] = D[0, j - 1] + 1
    # Solve
    for i in range(1, n):
        for j in range(1, m):
            subcost = 0 if source_word[i - 1] == target_word[j - 1] else 1
            D[i, j] = min(D[i - 1, j] + 1, D[i, j - 1] + 1, D[i - 1, j - 1] + subcost)
            
    if show_grid:
        print(D)
        
    return D[n - 1, m - 1]

In [3]:
#===============================
#           Assignment 2.4
# Compute the edit distance from "leda" to "deal"
#===============================

mineditdistance("leda", "deal", show_grid = True)

[[0. 1. 2. 3. 4.]
 [1. 1. 2. 3. 3.]
 [2. 2. 1. 2. 3.]
 [3. 2. 2. 2. 3.]
 [4. 3. 3. 2. 3.]]


3.0

In [4]:
#===============================
#           Assignment 2.5
# Is drive closer to brief or divers!
#===============================

print(mineditdistance("drive", "divers"))
print(mineditdistance("drive", "brief"))
# Edit distances are the same!

3.0
3.0


In [5]:
#===============================
#           Assignment 2.6
# The paper calculations are somewhere
#===============================